name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pandas numpy pydantic uvicorn

    - name: Test FastAPI app
      run: uvicorn server:app --host 0.0.0.0 --port 8000 & sleep 5 && curl -f http://localhost:8000

    - name: Deploy to DockerHub
      run: |
        docker build -t fatihxbayram/spam-classifier .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push your-dockerhub-username/spam-classifier
