name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List root directory contents for debugging
      run: ls -al

    - name: List full directory structure for debugging
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pandas numpy uvicorn

    - name: Start FastAPI app and run tests
      run: |
        if [ ! -d "Istdsa_MlOps_Project/spam_backend/app" ]; then
          echo "Directory Istdsa_MlOps_Project/spam_backend/app does not exist."
          exit 1
        fi
        cd Istdsa_MlOps_Project/spam_backend/app
        uvicorn server:app --host 0.0.0.0 --port 8000 --reload &
        sleep 10
        curl -v http://localhost:8000

    - name: Build Docker image
      run: docker build -t fatihxbayram/spam-classifier .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push fatihxbayram/spam-classifier
